---
- hosts: all
  tasks:
    - name: Create config directory if it doesn't exist
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_user_dir }}/.config/"

    - name: Symlink Neovim Lua configuration
      ansible.builtin.file:
        state: link
        src: "{{ ansible_user_dir }}/.dotfiles/{{ item }}"
        dest: "{{ ansible_user_dir }}/.config/{{ item }}"
      loop:
        - nvim

    - name: Create Neovim package directory for Packer
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/"
        recurse: yes

    - name: Clone packer.nvim repository
      ansible.builtin.git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
        depth: 1
