---
- hosts: all
  tasks:
    - file:
        state: link
        src: ~/.dotfiles/files/{{ item }}
        dest: ~/.{{ item }}
      with_items:
        - tmux.conf

    - git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
