---
- hosts: all
  tasks:
    - name: Symlink tmux configuration
      ansible.builtin.file:
        state: link
        src: "{{ ansible_user_dir }}/.dotfiles/files/{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
      loop:
        - tmux.conf

    - name: Clone tmux plugin manager (TPM)
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
        version: master
