---
- hosts: all
  tasks:
    - file:
        state: link
        src: ~/.dotfiles/files/{{ item }}
        dest: ~/.{{ item }}
      with_items:
        - vimrc

    - file:
        state: directory
        recurse: yes
        path: ~/.vim/{{ item }}
      with_items:
        - autoload

    - get_url:
        force: yes
        dest: ~/.vim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
