---
- hosts: all
  tasks:
    - file: src=~/.dotfiles/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - file: path=~/.vim/{{ item }} state=directory recurse=Yes
      with_items:
        - autoload

    - get_url:
        dest: ~/.vim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - shell: vim +PlugInstall +qall
